# P017 IRIS数据-加载认识数据

In [3]:
from sklearn.datasets import load_iris

In [5]:
iris = load_iris()

In [7]:
type(iris)

sklearn.utils._bunch.Bunch

In [9]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [27]:
iris.data[:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [29]:
iris.target[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# P018 IRIS数据-查看列名和分类名

In [32]:
iris["feature_names"]

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [40]:
import pandas as pd
pd.DataFrame(data=iris["data"], columns=iris["feature_names"])

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [44]:
iris["target_names"]

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

# P019 IRIS数据-数据和目标的shape

In [47]:
data = iris["data"]

In [49]:
type(data)

numpy.ndarray

In [51]:
data.shape

(150, 4)

In [53]:
target = iris["target"]

In [55]:
type(target)

numpy.ndarray

In [57]:
target.shape

(150,)

In [61]:
pd.Series(target).unique()

array([0, 1, 2])

# P020 IRIS数据-拆分训练测试集

In [68]:
data.shape

(150, 4)

In [70]:
target.shape

(150,)

In [72]:
from sklearn.model_selection import train_test_split

In [78]:
data_train, data_test, target_train, target_test = train_test_split(data, target, test_size=0.3)

In [80]:
data_train.shape

(105, 4)

In [84]:
target_train.shape

(105,)

In [92]:
data_test.shape

(45, 4)

In [94]:
target_test.shape

(45,)

# P021 IRIS数据-逻辑回归训练

In [97]:
from sklearn.linear_model import LogisticRegression

In [118]:
model = LogisticRegression(max_iter=1000)

In [120]:
model.fit(data_train, target_train)

LogisticRegression(max_iter=1000)

In [122]:
model.score(data_train, target_train)

0.9714285714285714

In [124]:
model.score(data_test, target_test)

0.9555555555555556

# P022 IRIS数据-在测试集实现预估

In [126]:
model

LogisticRegression(max_iter=1000)

In [128]:
data_test.shape

(45, 4)

In [130]:
target_pred = model.predict(data_test)

In [134]:
target_pred.shape

(45,)

In [136]:
target_pred

array([2, 1, 0, 1, 1, 1, 1, 1, 2, 0, 0, 2, 2, 1, 1, 2, 0, 1, 0, 0, 0, 1,
       0, 2, 2, 1, 0, 2, 0, 1, 0, 1, 1, 2, 2, 1, 2, 1, 2, 2, 2, 0, 0, 2,
       0])

In [138]:
target_test

array([2, 1, 0, 1, 1, 1, 1, 1, 2, 0, 0, 2, 2, 1, 2, 2, 0, 1, 0, 0, 0, 1,
       0, 2, 2, 1, 0, 2, 0, 1, 0, 1, 1, 2, 2, 1, 1, 1, 2, 2, 2, 0, 0, 2,
       0])

# P023 IRIS数据-理解混淆矩阵

In [141]:
from sklearn.metrics import confusion_matrix

In [143]:
confusion_matrix(target_test, target_pred)

array([[14,  0,  0],
       [ 0, 15,  1],
       [ 0,  1, 14]])

# P024 IRIS数据-理解分类报告

In [146]:
from sklearn.metrics import classification_report

In [148]:
classification_report(target_test, target_pred)

'              precision    recall  f1-score   support\n\n           0       1.00      1.00      1.00        14\n           1       0.94      0.94      0.94        16\n           2       0.93      0.93      0.93        15\n\n    accuracy                           0.96        45\n   macro avg       0.96      0.96      0.96        45\nweighted avg       0.96      0.96      0.96        45\n'

In [150]:
print(classification_report(target_test, target_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       0.94      0.94      0.94        16
           2       0.93      0.93      0.93        15

    accuracy                           0.96        45
   macro avg       0.96      0.96      0.96        45
weighted avg       0.96      0.96      0.96        45



In [152]:
print(classification_report(target_test, target_pred, target_names=iris["target_names"]))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        14
  versicolor       0.94      0.94      0.94        16
   virginica       0.93      0.93      0.93        15

    accuracy                           0.96        45
   macro avg       0.96      0.96      0.96        45
weighted avg       0.96      0.96      0.96        45

