# P039 数值标准化-读取CSV实现数值标准化

In [5]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [17]:
df = pd.read_csv("./p039.csv")

In [19]:
df

var1       var2       var3        var4      var5
0    13.960142  19.153902  79.572149  306.026051  0.102919
1    12.055207  19.379648  86.973172  363.574149  0.097459
2    14.413066  20.945469  83.899919  277.976782  0.107944
3    17.039090  14.889148  74.863005  454.959317  0.077539
4    11.767540  14.638630  79.008777  553.654226  0.102006
..         ...        ...        ...         ...       ...
138  14.910552  20.586392  87.543759  381.091369  0.101760
139   8.777407  23.358050  94.776316  294.820808  0.098683
140  13.152380  14.886554  71.440765  446.748652  0.094201
141  16.391428  24.999100  87.950515  483.741838  0.103641
142   7.647550  12.743737  91.674245  649.543731  0.099274

[143 rows x 5 columns]

In [21]:
scaler = StandardScaler()

In [23]:
scaler.fit(df)

StandardScaler()

In [25]:
df_scaled = scaler.transform(df)

In [27]:
df_scaled

array([[ 6.12496413e-01,  1.22067136e-01, -3.28169626e-01,
        -1.58021825e+00,  3.10098437e-01],
       [-5.86494151e-02,  1.94247210e-01,  5.19505211e-01,
        -1.00687698e+00, -2.17183695e-01],
       [ 7.72070062e-01,  6.94901113e-01,  1.67510688e-01,
        -1.85966803e+00,  7.95325986e-01],
       [ 1.69726945e+00, -1.24154124e+00, -8.67530613e-01,
        -9.64231194e-02, -2.14082961e+00],
       [-1.60000179e-01, -1.32164154e+00, -3.92695285e-01,
         8.86856372e-01,  2.21920496e-01],
       [-1.59982827e-01,  4.45618492e-01, -7.18980573e-01,
         1.66875313e+00,  7.38795358e-01],
       [ 1.75665250e+00,  2.29835971e-01, -8.29350703e-01,
         2.45801314e-01, -1.43342981e+00],
       [ 8.98636808e-01,  1.85240214e-01,  8.18767389e-01,
         1.79454218e+00,  1.09888250e+00],
       [-4.08724705e-01,  2.77282246e-01,  2.54584202e-01,
        -1.20298804e+00,  3.21270293e-01],
       [ 6.60953614e-01, -7.07328250e-01, -9.47945597e-01,
        -1.52506703e+00

# P040 数据标准化-训练测试集数值标准化

In [32]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [34]:
train = pd.read_csv("./p040-train.csv")
test = pd.read_csv("./p040-test.csv")

In [38]:
train.head()

var1   var2    var3    var4     var5
0  12.89  13.12   81.89   515.9  0.06955
1  13.40  20.52   88.64   556.7  0.11060
2  12.96  18.29   84.18   525.2  0.07351
3  17.75  28.03  117.30   981.6  0.09997
4  20.58  22.14  134.70  1290.0  0.09090

In [40]:
test.head()

var1   var2    var3    var4     var5
0  12.47  18.60   81.09   481.9  0.09965
1  18.94  21.31  123.60  1130.0  0.09009
2  15.46  19.48  101.70   748.9  0.10920
3  12.40  17.68   81.47   467.8  0.10540
4  11.54  14.44   74.65   402.9  0.09984

In [42]:
scaler = StandardScaler()

In [58]:
scaler.fit(train)

StandardScaler()

In [46]:
df_train = scaler.transform(train)

In [48]:
df_test = scaler.transform(test)

In [52]:
df_train[:3]

array([[-0.78798038, -1.50493922, -0.84666058, -0.74694047, -1.66784467],
       [-0.58782377,  0.18840344, -0.45859184, -0.58604615,  1.85926016],
       [-0.7605079 , -0.32188766, -0.71500467, -0.71026603, -1.3275929 ]])

In [56]:
df_test[:3]

array([[-0.95281523, -0.25095033, -0.89265391, -0.88101906,  0.91841247],
       [ 1.58642646,  0.36917921,  1.55131675,  1.67475559,  0.09699658],
       [ 0.22065195, -0.04957985,  0.29224929,  0.17189227,  1.73896913]])

In [60]:
scaler.var_

array([6.49232840e+00, 1.90973778e+01, 3.02545178e+02, 6.43041388e+04,
       1.35453299e-04])

In [62]:
scaler.mean_

array([1.48977778e+01, 1.96966667e+01, 9.66166667e+01, 7.05311111e+02,
       8.89611111e-02])